[package]
name = "zeroos-init"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[[bin]]
name = "init"
path = "src/main.rs"

[features]
acceptance = []

[dependencies]
libc.workspace = true
zeroos-storage = { path = "../storage", version = "=0.0.0" }

[lints]
workspace = true
